# Site Settings
locale                   : "pt-BR"
title                    : "CacheTOP"
title_separator          : "-"
name                     : &name "Alan"
description              : &description "contador de cacheta"
url                      : https://schirrel.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"